### ISSUE TITLE
Hugging face models?

### ISSUE THREAD

**Issue by YatongChen0603** [zechenli03/SensorLLM#2]
Hello authors, when can the pretrained hugging face models be released? Thanks!

**Comment by zechenli03** [comment]
Thank you for your interest in our work!

At the moment, we are still in the preprint phase and do not have plans to release the models. However, we are working on a training tutorial that will be available soon, allowing you to train the SensorLLM on your own datasets!

Stay tuned, and we appreciate your patience and understanding.
